package com.xiaopo.flying.layoutmaster.property

/**
 * @author wupanjie on 2018/4/5.
 */
object Gravity {
  val NO_GRAVITY = 0x0000

  private val AXIS_SPECIFIED = 0x0001

  private val AXIS_PULL_BEFORE = 0x0002
  private val AXIS_PULL_AFTER = 0x0004
  private val AXIS_CLIP = 0x0008

  private val AXIS_X_SHIFT = 0
  private val AXIS_Y_SHIFT = 4

  val TOP = AXIS_PULL_BEFORE or AXIS_SPECIFIED shl AXIS_Y_SHIFT
  val BOTTOM = AXIS_PULL_AFTER or AXIS_SPECIFIED shl AXIS_Y_SHIFT
  val LEFT = AXIS_PULL_BEFORE or AXIS_SPECIFIED shl AXIS_X_SHIFT
  val RIGHT = AXIS_PULL_AFTER or AXIS_SPECIFIED shl AXIS_X_SHIFT

  val CENTER_VERTICAL = AXIS_SPECIFIED shl AXIS_Y_SHIFT
  val FILL_VERTICAL = TOP or BOTTOM

  val CENTER_HORIZONTAL = AXIS_SPECIFIED shl AXIS_X_SHIFT
  val FILL_HORIZONTAL = LEFT or RIGHT

  val CENTER = CENTER_VERTICAL or CENTER_HORIZONTAL

  val FILL = FILL_VERTICAL or FILL_HORIZONTAL

  val CLIP_VERTICAL = AXIS_CLIP shl AXIS_Y_SHIFT

  val CLIP_HORIZONTAL = AXIS_CLIP shl AXIS_X_SHIFT

  private val RELATIVE_LAYOUT_DIRECTION = 0x00800000

  val START = RELATIVE_LAYOUT_DIRECTION or LEFT

  val END = RELATIVE_LAYOUT_DIRECTION or RIGHT
}
